### ISSUE TITLE
Remove dead code

### ISSUE THREAD

**Issue by zeguru** [Software-Elegance/classif-ai#4]
Some modules contain very little code hence the need to move those classes to a new home and drop the module

**Comment by AnushreeDixit** [comment]
> Some modules contain very little code hence the need to move those classes to a new home and drop the module

Can I start working on it ? @zeguru

**Comment by Mfuon2** [comment]
> 

@AnushreeDixit We are setting up some configurations will be able to give you a green light to proceed. Otherwise you can explore the source in the mean time
